# Generated by Django 3.2.9 on 2021-12-09 16:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companyLogo', models.ImageField(upload_to='')),
                ('companyEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('Host_phone_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compLogo', models.ImageField(upload_to='images')),
                ('compName', models.CharField(max_length=50)),
                ('compEmail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitorId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('Visitors_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pourpose', models.CharField(max_length=100)),
                ('blacklisted', models.IntegerField()),
                ('imageurl', models.TextField(max_length=20000)),
                ('visitor_company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInDate', models.DateField(blank=True, null=True)),
                ('checkOutDate', models.DateField(blank=True, null=True)),
                ('checkInTime', models.TimeField(blank=True, null=True)),
                ('checkOutTime', models.TimeField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('cheakedINinfo', models.IntegerField(null=True)),
                ('schedukevisit', models.IntegerField(default=0)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_pin', models.IntegerField(null=True, unique=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiters.host')),
                ('visitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiters.visitors')),
            ],
        ),
        migrations.CreateModel(
            name='print_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('checkin_Time', models.TimeField(blank=True, null=True)),
                ('checkout_Date', models.DateField(blank=True, null=True)),
                ('host_name', models.CharField(max_length=50, null=True)),
                ('imageurl', models.TextField(max_length=10000)),
                ('status', models.IntegerField(default=0)),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiters.visit')),
            ],
        ),
    ]
