# Generated by Django 3.2.9 on 2021-12-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('role', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('forget_password_token', models.CharField(max_length=100, null=True)),
                ('login_time', models.TimeField(null=True)),
                ('logout_time', models.TimeField(null=True)),
            ],
        ),
    ]
