services:
  - type: web
    name: vizit-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn MainWeb.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vizit-db
          property: connectionString

databases:
  - name: vizit-db
